### ISSUE TITLE
Prusa Slic3r: Hollowing leads to bridge infill

### ISSUE THREAD

**Issue by BAndiT1983** [andysc/Quantum#1]
Hi, 
while trying to print the model, some strange rips occurred. After inspecting the layers in Prusa Slic3r again, I've noticed that bridge infills are created over the whole model diagonally, which results in ripping up, as the material is not connected to anything below and the heat twists the bridges.

Looked at SCAD file and seen that it hollows the parts out. Could you provide a version, without hollow inside, please?

**Comment by andysc** [comment]
Hi - it's meant to be hollow, and printed in lots of different bits and then assembled.
There's a printing schedule which lists all the STLs that need to be printed.
Are you trying to print the whole model in one go? 
Which STL are you seeing this problem with?

**Comment by BAndiT1983** [comment]
No, not as whole. What i meant about hollow, the insides of individual parts as lid or base. It looks like the insides are not there, so the slicer plans bridge infills and not proper infill like gyroid, grid etc.

This is the result from the STLs in the repo, all 4 panels, which were printing at once, looked like that:
![IMG_2020-07-02-11-43-08-786](https://user-images.githubusercontent.com/1292541/86343917-ddf2a780-bc59-11ea-9e6b-fa557ea95526.jpg)

**Comment by andysc** [comment]
OK - let's talk about one STL in particular, so we're on the same page... lid.stl ?
that is meant to be hollowed-out, as the wire runs through it, and base_lid clips into the top.
You have to flip it over so it's "bottom-down", of course.
What is the STL file you posted the photo of?

**Comment by BAndiT1983** [comment]
The STL was flipped (am not new to 3D printing), as there is not much point to print it upside down and having a lot of supports and coarse surface. 

File could be lid.stl, but all 4 are looking similar (besides one with the hole), as there was collision detected and printer stopped, so cannot distinguish them that much.

**Comment by andysc** [comment]
In that case I'm not sure what you're asking me to fix?
A flat panel is a flat panel, made with "cube" in openSCAD, so it's not hollow "inside" (your slicer does whatever it needs to for internal infill).
And a "box" (like lid.stl) that's hollowed-out should have "nothing" in the empty inside (as we subtract a cube from the solid block we started with), so that shouldn't cause any artefacts in the STL, and I haven't seen that happen anywhere else these have been printed.

**Comment by BAndiT1983** [comment]
Ok, then, then i will continue to search for some solution myself. Never had a problem with my printer before and mostly printing my own stuff, which was done in Fusion360.

Also not sure why the model needs that many parts to print, so will possibly recreate it differently for my needs.

**Comment by andysc** [comment]
I'd be interested to know why it's doing this. I'll see if I can find someone else with a Prusa to try it. 

And yes, if you'd like to make a version with fewer parts, that would be great.

I have electronics in various places, so need the internal spaces. I guess the base could be one piece, but I wanted to hide the wire.
The very top box ("lid") (above the light box) is hollow in anticipation of v2 which has an OLED display at the top.
And the back box has a Raspberry PiZeroW inside... so there isn't much reduction of parts that can be done for my needs.

**Comment by BAndiT1983** [comment]
Have checked Prusa forum, also related SCAD issues and disabled "Ensure vertical shell thickness" option, with this the bridge infills are gone, the object is solid now, as it's rather thin by itself. The downside there is the long printing time, although the infill is set to 20%, but not used, slicer says 4h 8m for lid, lid_lower, base and base_lid. 

The project was forwarded to me by someone who works at IBM and i was asked to print it. So the interest to replicate it and possibly improve is there.

**Comment by andysc** [comment]
That seems a reasonable time to print all of those (I assume it's together, not each) :)

I'm surprised the infill "spills out" onto the top - surely it should all stay inside... 
what size nozzle are you using? 

How thin is "rather thin" in your book?
I see lid_lower and base_lid are 4mm thick (maybe a bit excessive with hindsight) - I would have thought the infill algorithm should be able to deal with that... I use 30% infill (the default) on mine.

If the someone who works at IBM wants to contact me, they're very welcome to :)

**Comment by BAndiT1983** [comment]
Usually it should print faster if there is infill and not solid layer, at least from my experience. But with 0.2mm layer height, there are only 6 layers or so and that i would consider as rather thin. Referring solely to the base of the lid, without considering the walls.

The infill is not used, as shell thickness is set to 2 by default. Have to play around with print settings a bit more, it could help to accelerate this. Usually printing a lot faster, especially with gyroid infill.

Using standard 0.4mm nozzle on the Prusa MK3S.

Will forward your message to the person.

**Comment by andysc** [comment]
OK - I *do* assume infill ... it's just a default on my slicer. Perhaps I should mention that in the notes.
But then I can see how shell thickness could get in the way of that on yours... is that "2" mm or layers?

**Comment by BAndiT1983** [comment]
The 2 is referring to layers here, seen also that there are more layers set for the bottom on different presets, like 4, before it starts to add infill, will check it a bit later. Am adjusting settings only when required, e.g. printing something a bit more complicated. Usually Prusa presets are rather to the point for me, even for such stuff like nut/screw pockets.
